### ISSUE TITLE
Pin2Action does not work on firmware 10.4.3

### ISSUE THREAD

**Issue by superbraz** [aintegration/SolutionsLab#2]
Hey,
i use the pin2action aplication for our daughter - she can open the door by entering a pincode.
works fine on firmware 1.97.2.2 - but not on the newest 10.4.3.

thanks for help!

**Comment by aintegration** [comment]
Hi,
thanks a lot for the notice.
The issue is caused by a change of the internal communication in the firmware due to security concerns. Unfortunately, an alternative method for us to retrieve PIN codes won't be available until the release of firmware 10.6 which is scheduled for autumn 2021. I am hoping for a service release or perhaps at least a test firmware to get this function working again. Once the firmware is available, I will also publish a new version of Pin2Action.
Best regards
Willi

**Comment by superbraz** [comment]
thank you very much! so i can wait until autumn and install a new firmware, if a new version of pin2action is released.
big thanks for your answer :)

**Comment by aintegration** [comment]
I have published an updated version of Pin2Action (0.1.3) together with a beta version of the firmware as a temporary fix. Please give it a try.

**Comment by superbraz** [comment]
FW 10.5.0 was released - pin2action 0.1.3 will not work on it
